### ISSUE TITLE
dosbox-staging does not start on ubuntu 21.10

### ISSUE THREAD

**Issue by sampie** [popey/dosbox-staging-snap#10]
Dosbox-staging does not start, but gives instead following errors:

dosbox-staging version 0.76.0
---
/usr/share/libdrm/amdgpu.ids: No such file or directory
si_init_perfcounters: max_sh_per_se = 2 not supported (inaccurate performance counters)
X Error:  BadAlloc
  Request Major code 146 ()
  Request Minor code 2
  Error Serial #100
  Current Serial #101

**Comment by popey** [comment]
The snap has now been updated, and starts here on 21.10.
I'm going to close this, but do respond if it recurrs.
