### ISSUE TITLE
Please update or pull the snap package

### ISSUE THREAD

**Issue by kcgen** [popey/dosbox-staging-snap#11]
It is now more than a year (and several releases) out of date.

However, if the snap metadata can remain available, I'm sure it can be a good springboard to update it to the current version (if a volunteer wants to do so).

**Comment by popey** [comment]
See this thread: https://forum.snapcraft.io/t/looking-for-someone-to-maintain-some-snaps/28354?u=popey

**Comment by kcgen** [comment]
The current version is unfortunately causing problems for users and myself. They are reading documentation and telling me that features are broken and unsupported (or it's just crashing). 

I appreciate asking for someone to take this off your plate - but until that help materializes, can you please remove the DOSBox Staging snap package or block users from getting it? Thanks @popey.

**Comment by popey** [comment]
I've spent some significant time this weekend updating the package to the latest stable release - 0.78.1
So this gets past the issue of it being outdated, until someone else can take it on. It should continue to build to the edge channel when new releases are made upstream, unless something significant breaks.

Are there specific issues with the snap which we can look at?

**Comment by kcgen** [comment]
Thanks @popey ,

These are the main issues:

https://github.com/dosbox-staging/dosbox-staging/issues/597

https://github.com/dosbox-staging/dosbox-staging/issues/720

https://github.com/dosbox-staging/dosbox-staging/issues/1107

**Comment by Grounded0** [comment]
@kcgen i suggest closing this ticket as all the issues have been resolved. Thanks to @popey for hard work on keeping our Linux side of things viable and up to date.
