### ISSUE TITLE
dosbox-staging 0.80.0 is out

### ISSUE THREAD

**Issue by Recydywa** [popey/dosbox-staging-snap#13]
The snap is still at version 0.78.1 in all of the channels.

Meanwhile there were 0.79.0 and 0.79.1 releases. And the newest release 0.80.0 was almost a week ago.

https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.80.0

Please update the snap version when you find the time to do it.

**Comment by popey** [comment]
Thanks for filing this issue.

I have previously requested someone to take on this (and other) snap maintenance. Sadly no takers. https://forum.snapcraft.io/t/looking-for-someone-to-maintain-some-snaps/28354

The snap fails to build currently. If I have time, I'll try and get it working again. But I'd much rather someone else took it over.

**Comment by Recydywa** [comment]
The snap is now at version 0.81.0 so the issue is resolved.
