### ISSUE TITLE
dosbox-staging 0.75.1 is out

### ISSUE THREAD

**Issue by dreamer** [popey/dosbox-staging-snap#5]
Detailed info here: https://dosbox-staging.github.io/v0-75-1/

I looked at yaml file thinking there will be some simple field to update tag name, so I could send a quick PR but I am not sure what's `override-pull` section in the file is expected to accomplish.

If it's of any help: we use `master` to push development forward, stable releases have their own branches; e.g. new release is a tag on `release/0.75.x` branch. Once next release will be stabilized we'll create `release/0.76.x` branch, etc.

I hope we'll be able to take over ownership over snap package for future 0.76.0 release (mostly because Ubuntu 18.04 is missing FluidSynth 2.x in the repos) - but for 0.75.1 - please update it at your convenience :)

**Comment by popey** [comment]
Apologies for the lengthy delay. The snap is now up to date.
