### ISSUE TITLE
dosbox-staging 0.77.0 is out

### ISSUE THREAD

**Issue by Recydywa** [popey/dosbox-staging-snap#9]
The previous version was released in December and this new one is already 22 days old.

https://dosbox-staging.github.io/v0-77-0/

**Comment by archisman-panigrahi** [comment]
Version 0.78.1 has been released. https://github.com/dosbox-staging/dosbox-staging/releases/tag/v0.78.1

**Comment by popey** [comment]
Thanks for the issue. This has been released.
